# Basic Site Settings

locale                   : "en-US"
site_theme               : "default" 
title                    : "Badrudeen Yusuf Akinkunmi"
title_separator          : "-"
name                     : &name "Badrudeen Yusuf Akinkunmi"
description              : &description "Cybersecurity Researcher | SOC Analyst | AI for Autonomous Systems Security"
url                      : https://yusbad09.github.io
baseurl                  : "" 
repository               : "yusbad09/yusbad09.github.io"

author:
  avatar     : ""Profile_Picture.jpg""
  name       : "Badrudeen Yusuf Akinkunmi"
  pronouns   : "He/Him"  
  bio        : "Cybersecurity Researcher | SOC Analyst | AI-driven Security for Autonomous Systems"
  location   : "Nigeria"
  employer   : "Huawei Technologies / Independent Researcher"
  email      : "badrudeenyusuf55@gmail.com" 
  linkedin   : "badrudeen-yusuf-akinkunmi-6692b819b"
  twitter    : "yusbad09"

  # Custom CV download link
  cv_link    : "/files/BADRUDEEN YUSUF AKINKUNMI IDAN ACADEMIC CV.pdf"


  # Repositories and software development
  github           : "https://github.com/Yusbad09"

  # Social media
  linkedin         : "https://www.linkedin.com/in/badrudeen-yusuf-akinkunmi-6692b819b/"
  twitter          : "https://x.com/yusbad09"   

# Publication Category 
publication_category:
#   books:
#     title: 'Books'
#   manuscripts:
#     title: 'Journal Articles'    
#   conferences:
#     title: 'Conference Papers'

# Site Settings
teaser                   :  
breadcrumbs              : false 
words_per_minute         : 160
future                   : true
read_more                : "disabled"
comments:
  provider               : false

atom_feed:
  hide                   : false     

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Analytics
analytics:
  provider               :  "false" 

# Reading Files
include:
  - .htaccess
  - _pages
  - files

# Collections
collections:
  teaching:
  #   output: true
  #   permalink: /:collection/:path/
  # publications:
  #   output: true
  #   permalink: /:collection/:path/
  # portfolio:
  #   output: true
  #   permalink: /:collection/:path/
  # talks:
  #   output: true
  #   permalink: /:collection/:path/


defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: home
      author_profile: true
